# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be2320848faf4dbabd08cb4d84c5e04add3471a57a2c13f0e8308a5b5e57587fae4612d331f6d5534531a7727135c82ce229c6184a2cafad8e01dd88fb5697d1

test:
  secret_key_base: 46e36ef13257b6a0b052583e990d8dba0165333473007ef56a1e9c7689616995b7e53deb819f66171ea4e672ff2400d78fe5b97cc0c18d7c209c78231bb8dd26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
